### ISSUE TITLE
Reduce Snowflake logging during invocation

### ISSUE THREAD

**Issue by holly-evans** [MeltanoLabs/target-snowflake#269]
## Description

target-snowflake emits many log entries from the `snowflake.connector`

To reduce this, package a default logging configuration for target-snowflake to remove these from INFO

## References
* https://meltano.slack.com/archives/C069A0GE129/p1727185612524059
* https://github.com/MeltanoLabs/target-snowflake/blob/81f4466422bceb5e84473825b32fdfcaf704a80e/target_snowflake_logging.yaml

**Comment by edgarrmondragon** [comment]
Thanks for logging!

**Comment by chadcampling-opteon** [comment]
Is this one just as simple as changing the logging config at https://github.com/MeltanoLabs/target-snowflake/blob/main/target_snowflake_logging.yaml to be INFO and not DEBUG as it is now? 

The logging from the snowflake.connector.cursor is making my logs unreadable in cloudwatch while trying to diagnose an issue.

Happy to push a PR if I'm not missing something!

**Comment by edgarrmondragon** [comment]
> Is this one just as simple as changing the logging config at https://github.com/MeltanoLabs/target-snowflake/blob/main/target_snowflake_logging.yaml to be INFO and not DEBUG as it is now?
> 
> Happy to push a PR if I'm not missing something!

You actually need to package the logging configuration file, so that file won't do and we'd like to keep to output debug logs in CI here. So, https://github.com/MeltanoLabs/target-snowflake/pull/299 should do it. Can you confirm the logs are less spam-y with that?
