### ISSUE TITLE
Joins with Nulls

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-snowflake#44]
https://github.com/MeltanoLabs/target-snowflake/blob/main/target_snowflake/sinks.py#L248

@kgpayne 

Instead of `table.name = othertable.name` try `table.name IS DISTINCT FROM othertable.name` 3 valued logic is fun!

**Comment by pnadolny13** [comment]
This should have been resolved by these PRs:

- https://github.com/MeltanoLabs/target-snowflake/pull/55
- https://github.com/MeltanoLabs/target-snowflake/pull/51
- https://github.com/MeltanoLabs/target-snowflake/pull/46

Reserved words and casing shouldnt affect the comparisons anymore. I'm going to close this for now but if someone runs into this again please reopen the issue.
