### ISSUE TITLE
ImportError: cannot import name 'SQLConnector' from 'singer_sdk.sinks'

### ISSUE THREAD

**Issue by pnadolny13** [MeltanoLabs/target-snowflake#6]
```
Traceback (most recent call last):
  File "/Users/pnadolny/Documents/Git/GitHub/pnadolny/hub-utils/hub_utils/test_meltano_project/.meltano/loaders/target-snowflake/venv/bin/target-snowflake", line 5, in <module>
    from target_snowflake.target import TargetSnowflake
  File "/Users/pnadolny/Documents/Git/GitHub/pnadolny/hub-utils/hub_utils/test_meltano_project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/target_snowflake/target.py", line 8, in <module>
    from target_snowflake.sinks import SnowflakeSink
  File "/Users/pnadolny/Documents/Git/GitHub/pnadolny/hub-utils/hub_utils/test_meltano_project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/target_snowflake/sinks.py", line 17, in <module>
    from singer_sdk.sinks import SQLConnector, SQLSink
ImportError: cannot import name 'SQLConnector' from 'singer_sdk.sinks' (/Users/pnadolny/Documents/Git/GitHub/pnadolny/hub-utils/hub_utils/test_meltano_project/.meltano/loaders/target-snowflake/venv/lib/python3.8/site-packages/singer_sdk/sinks/__init__.py)
Command '['poetry', 'run', 'meltano', 'invoke', 'target-snowflake', '--help']' returned non-zero exit status 1.
Configuration file exists at /Users/pnadolny/Library/Application Support/pypoetry, reusing this directory.
```

@kgpayne I was trying to add this to the hub and it threw an error before I could extract the `--about` metadata, in this case during a `--help` command.

**Comment by JulesHuisman** [comment]
I am running into the same issue.

**Comment by pnadolny13** [comment]
cc @kgpayne @edgarrmondragon

**Comment by JulesHuisman** [comment]
I can't create a PR right now, but I think:
https://github.com/MeltanoLabs/target-snowflake/blob/d9f6be6d2441bd4ecb55d875d26abe3f6e149ab0/target_snowflake/sinks.py#L17
should be `from singer_sdk.sinks.sql import SQLConnector, SQLSink `

**Comment by edgarrmondragon** [comment]
I'm working on a PR but a temporary workaround is to pin the SDK version to `0.13.0` in the `pip_url`

```yaml
pip_url: meltanolabs-target-snowflake singer_sdk==0.13.0
```

or if not using Meltano:

```
pipx install meltanolabs-target-snowflake 
pipx inject meltanolabs-target-snowflake singer_sdk==0.13.0
```

**Comment by aaronsteers** [comment]
Logged root cause for discussion/analysis:

- https://github.com/meltano/sdk/issues/1336

@pnadolny13 - Have you been blocked since November on using `target-snowflake`, or do you have a workaround?

**Comment by pnadolny13** [comment]
@aaronsteers I opened this issue while I was trying to add this target to the hub but I havent spent time trying to use it to replace the pipelinewise variant in Squared. I wasnt clear what the status was of this target given that it has only 4 commits and a bunch of TODOs in the readme still, I assumed it was in initial development still. All to say, no https://github.com/meltano/sdk/issues/1336 was not blocking me yet.
