### ISSUE TITLE
Consider adding credentials to Dependabot app

### ISSUE THREAD

**Issue by edgarrmondragon** [MeltanoLabs/target-snowflake#72]
Currently CI checks are failing in Dependabot PRs because secrets have not been added to the app:

<img width="1121" alt="Screenshot 2023-07-07 at 10 28 39" src="https://github.com/MeltanoLabs/target-snowflake/assets/16805946/7331a83b-b972-42e3-9b60-2fea62146224">

**Comment by pnadolny13** [comment]
Done!
